//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_205_PhilsLab_UNitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResultsRemastered
    {
        public int TestResultRemasteredId { get; set; }
        public string TestName { get; set; }
        public bool TestPassed { get; set; }
        public Nullable<int> Range { get; set; }
        public Nullable<long> TotalSum { get; set; }
        public Nullable<long> TimeElapsed { get; set; }
    }
}
