//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_200._2_PhilsLab_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResultsNew
    {
        public int TestResultNewId { get; set; }
        public string TestName { get; set; }
        public int Range { get; set; }
        public long TotalSum { get; set; }
        public long TimeElapsed { get; set; }
    }
}
